---
  name: secops
  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  jobs:
    # run trufflehog on all files in the repository
    trufflehog:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run trufflehog
          run: docker run --rm -v $(pwd):/project -w /project adamcaudill/trufflehog --json .